### ISSUE TITLE
Example Create CallList

### ISSUE THREAD

**Issue by fixNoobi** [voximplant/apiclient-go#2]
Hello, please add example how to create call list.

**Comment by DmitryIvaneychik** [comment]
voxConfig := config.NewConfig().WithKeyPath("PATH_TO_JSON_CREDENTIALS.json")

	// Init client
	client, err := methods.NewClient(voxConfig)

	if err != nil {
		panic("failed to create client, " + err.Error())
	}

	// Demo data array
	records := [][]string{
		{"__start_execution_time", "__end_execution_time", "client_name", "client_phone"},
		{"07:00:00", "15:00:00", "Rob", "79991234567"},
		{"07:00:00", "15:00:00", "John", "79991234567"},
		{"07:00:00", "15:00:00", "Jack", "79991234567"},
	}

	// Convert data to CSV
	data := &bytes.Buffer{}
	writer := csv.NewWriter(data)
	err = writer.WriteAll(records)
	if err != nil {
		panic("failed to convert, " + err.Error())
	}

	writer.Flush()

	// Build input parameters
	params := methods.CreateCallListParams{
		RuleId: 1, // Your ruleID
		NumAttempts: 1,
		MaxSimultaneous: 1,
		Name: "Demo list2",
		Delimiter: ",",
		FileContent: data.String(),
	}


	// Send the request and get the response or error back
	res, verr, err := client.CallLists.CreateCallList(params)

	// Return results
	fmt.Println(res, verr, err)
